esphome:
  name: led-clock
  friendly_name: led-clock

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "JlgLuV0KkE2S9vYCIeCN0x20Pf37tf01KZX2AuD+pUk="

ota:
  - platform: esphome
    password: "83ddf83fb8b66d4c0a37d1ad79fdf219"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Led-Clock Fallback Hotspot"
    password: "Lw18671EQsT0"

captive_portal:

# UART für Kommunikation mit Arduino
uart:
  id: uart_bus
  tx_pin: GPIO1  # TXD0 TX GPIO1
  rx_pin: GPIO3  # RXD0 Rx GPIO3 // Only TX is necessary. State is not read from device.
  baud_rate: 9600

# Zeit von Home Assistant synchronisieren
time:
  - platform: homeassistant
    id: homeassistant_time
    on_time_sync:
      then:
        - uart.write: "status\n"  # Status abfragen, um Zeit zu prüfen

# Switch für Display On/Off
switch:
  - platform: template
    name: "LED Clock Display"
    id: display_switch
    optimistic: true
    turn_on_action:
      - uart.write: "on\n"
    turn_off_action:
      - uart.write: "off\n"

button:
  - platform: template
    name: "LED Clock Sync Time"
    on_press:
      then:
        - lambda: |-
            auto now = id(homeassistant_time).now();
            char time_str[9];
            snprintf(time_str, sizeof(time_str), "%02d:%02d:%02d\n",
                     now.hour, now.minute, now.second);
            // Sende die formatierte Zeit als Byte-Array
            id(uart_bus).write_array((const uint8_t *)time_str, strlen(time_str));
            // Optional: Bestätigung im Log
            ESP_LOGD("LED Clock", "Zeit synchronisiert: %s", time_str);